# Site settings
title: Martinique
client:
  name: Die Blume der Karibik
  link: "http://bit.ly/2AEY6ye"
  link2: "https://de.france.fr/de/martinique?utm_source=LogoFrance_SecretEscapes&utm_campaign=Martinique_SecretEscapes&utm_medium=display&utm_term=nov_2018"
core-se-link: https://www.secretescapes.de/aktuelle-angebote
description: >
  Mitten in der Karibik und zugleich ein Teil Europas, trifft dort Regenwald auf Sandstrand, schillernde Unterwasserwelt auf wüstenartige Savanne und exotische Vegetation auf europäische Hotelstandards.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/de/martinique" # the subpath of your site, e.g. /blog/
img:     "/de/martinique/_assets/img"
css:     "/de/martinique/_assets/css"
js:      "/de/martinique/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed
